SRIS/SRIS/Controllers/CaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SRIS.SPI;
using SRIS.ViewModels;
using SRIS.Model;
using Newtonsoft.Json;

namespace SRIS.Controllers
{
    public class CaseController : Controller
    {
        IRegisterInfo IRegisterInfo;
        public CaseController()
        {
            IRegisterInfo = new BLL.RegisterInfoBLL();
        }
        // GET: Case
        public ActionResult AllCase()
        {
            return View();
        }

        /// <summary>
        /// 获取所有案例信息
        /// </summary>
        /// <returns></returns>
        public string GetAllCase(int page,int limit,string whereStr)
        {
            int pageCount;
            Dictionary<string, string> whereDic = null;
            if (!string.IsNullOrEmpty(whereStr))
            {
                whereDic = JsonConvert.DeserializeObject<Dictionary<string, string>>(whereStr);
            }
            string userId = Session["userId"].ToString();
            List<RegisterInfo> list = IRegisterInfo.GetAllCaseInfo(userId, page,limit, whereDic, out pageCount);
            List<RegisterModel> modelList = new List<RegisterModel>();
            foreach (RegisterInfo item in list)
            {
                RegisterModel model = new RegisterModel();
                model.BeSeekerName = item.BeSeekerName;
                model.CaseCode = item.CaseCode;
                model.getTaskDate = item.GetTaskDateTime.ToShortDateString();
                model.IsBBHJ = item.IsBBHJ;
                model.IsReturnTask = item.IsReturnTask;
                model.PostLink = item.PostLink;
                model.RegisterInfoId = item.RegisterInfoID;
                model.RegisterLink = item.RegisterLink;
                model.Remarks = item.Remarks;
                model.SRTypeId = item.SRTypeID;
                model.SRTypeName = item.SRType.SRTypeName;
                model.Title = item.Title;
                modelList.Add(model);
            }
            RegisterCaseInfo data = new RegisterCaseInfo()
            {
                code = 0,
                count = pageCount,
                data = modelList,
                msg = ""
            };
            return JsonConvert.SerializeObject(data);
        }

        /// <summary>
        /// 创建案例
        /// </summary>
        /// <returns></returns>
        public ActionResult CreateCase(string id="")
        {
            RegisterInfo model = IRegisterInfo.GetRegisterInfoById(id);
            if (model == null)
            {
                SRTypelist();
                return View();
            }
            else
            {
                RegisterModel viewModel = new RegisterModel()
                {
                    BeSeekerName = model.BeSeekerName,
                    CaseCode = model.CaseCode,
                    GetTaskDateTime = model.GetTaskDateTime,
                    //getTaskDate=model.GetTaskDateTime.ToShortDateString(),
                    PostLink = model.PostLink,
                    RegisterInfoId = model.RegisterInfoID,
                    RegisterLink = model.RegisterLink,
                    Remarks = model.Remarks,
                    SRTypeId = model.SRTypeID,
                    Title = model.Title
                };
                SRTypelist();
                return View(viewModel);
            }
        }

        [HttpPost]
        public ActionResult CreateCase(RegisterModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    RegisterInfo md = IRegisterInfo.GetRegisterInfoById(model.RegisterInfoId);
                    if (md == null)
                    {
                        // 创建
                        RegisterInfo registerinfoModel = new RegisterInfo()
                        {
                            BeSeekerName = model.BeSeekerName,
                            CaseCode = model.CaseCode,
                            CreateDateTime = DateTime.Now,
                            DNAState = null,
                            GetTaskDateTime = model.GetTaskDateTime,
                            IsBBHJ = "0",
                            IsReturnTask = 0,
                            PostLink = "",
                            RegisterLink = model.RegisterLink,
                            RegisterInfoID = Guid.NewGuid().ToString(),
                            Remarks = model.Remarks,
                            ReturnReason = "",
                            ReturnTaskDateTime = null,
                            SRTypeID = model.SRTypeId,
                            Title = model.Title,
                            UserInfoID = Session["userId"].ToString()
                        };
                        if (IRegisterInfo.CreateRegister(registerinfoModel))
                        {
                            return RedirectToAction("AllCase");
                        }
                    }
                    else
                    {
                        // 修改
                        md.BeSeekerName = model.BeSeekerName;
                        md.CaseCode = model.CaseCode;
                        md.GetTaskDateTime = model.GetTaskDateTime;
                        md.PostLink = "";
                        md.RegisterLink = model.RegisterLink;
                        md.PostLink = model.PostLink==null?"":model.PostLink;
                        md.Remarks = model.Remarks;
                        md.SRTypeID = model.SRTypeId;
                        md.Title = model.Title;
                        md.RegisterInfoID = model.RegisterInfoId;
                        if (IRegisterInfo.UpdateRegisterInfo(md))
                        {
                            return RedirectToAction("AllCase");
                        }
                    }



                }
                SRTypelist();
                return View(model);
            }
            catch (Exception e)
            {
                ViewBag.Message = e.Message;
                SRTypelist();
                return View(model);
            }
        }

        private void SRTypelist()
        {
            // 获取所有的案例类型
            List<SelectListItem> itemList = new List<SelectListItem>();
            List<SRType> SRTypeList = IRegisterInfo.GetSRType();
            SRTypeList.ForEach(o => {
                SelectListItem item = new SelectListItem()
                {
                    Value = o.SRTypeID.ToString(),
                    Text = o.SRTypeName
                };
                itemList.Add(item);
            });
            SelectList select = new SelectList(itemList, "Value", "Text");
            ViewBag.select = select;
        }

        public ActionResult EditCase(string caseId)
        {
            LinkMan model = IRegisterInfo.GetLinManModelById(caseId);
            if (model == null)
            {
                return View();
            }
            else
            {
                LinkManModel viewModel = new LinkManModel()
                {
                    Address = model.Address,
                    Birthday = model.Birthday,
                    Career = model.Career,
                    Email = model.Email,
                    IdCardNo = model.IdCardNo,
                    LinkManName = model.LinkManName,
                    OtherLink = model.OtherLink,
                    Phone = model.Phone,
                    QQ = model.QQ,
                    Relationship = model.Relationship,
                    Remark = model.Remark,
                    Sex = model.Sex,
                    TelPhone = model.TelPhone,
                    WeiXin = model.WeiXin,
                    LinkManID = model.LinkManID
                };
                return View(viewModel);
            }
        }

        public ActionResult EditLinManInfo(string id)
        {
            LinkMan model = IRegisterInfo.GetLinManModelById(id);
            if (model == null)
            {
                LinkManModel viewModel = new LinkManModel() {
                    RegisterInfoId=id
                };
                return View(viewModel);
            }
            else
            {
                LinkManModel viewModel = new LinkManModel() {
                    Address = model.Address,
                    Birthday=model.Birthday,
                    Career=model.Career,
                    Email=model.Email,
                    IdCardNo=model.IdCardNo,
                    LinkManName=model.LinkManName,
                    OtherLink=model.OtherLink,
                    Phone=model.Phone,
                    QQ=model.QQ,
                    Relationship=model.Relationship,
                    Remark=model.Remark,
                    Sex=model.Sex,
                    TelPhone=model.TelPhone,
                    WeiXin=model.WeiXin,
                    LinkManID=model.LinkManID,
                    RegisterInfoId=model.RegisterInfoId
                };
                return View(viewModel);
            }
        }

        [HttpPost]
        public ActionResult EditLinManInfo(LinkManModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    LinkMan LinManmodel = IRegisterInfo.GetLinManModelById(model.RegisterInfoId);

                    if (LinManmodel == null)
                    {
                        // 新建
                        LinkMan linkMan = new LinkMan()
                        {
                            Address = model.Address,
                            Birthday = model.Birthday,
                            Career = model.Career,
                            CreateDateTime = DateTime.Now,

SRIS/SRIS/Views/Case/AllCase.cshtml
@model SRIS.ViewModels.RegisterModel
@{
    ViewBag.Title = "全部案例";
    Layout = "~/Views/Shared/_BlankPage.cshtml";
}
<body>
    <div class="main-content">
        <div class="main-content-inner">
            <div class="breadcrumbs" id="breadcrumbs">
                <script type="text/javascript">
                    try { ace.settings.check('breadcrumbs', 'fixed') } catch (e) { }
                </script>
                <ul class="breadcrumb">
                    <li>
                        <i class="ace-icon fa fa-home home-icon"></i>
                        @Html.ActionLink("首页", "Index", "Home")
                    </li>
                    <li>
                        @Html.ActionLink("全部案例", "AllCase", "Case")
                    </li>
                </ul><!-- /.breadcrumb -->
            </div>

            <div style="margin-left: 20px; margin-top:20px">
               
                <div class="demoTable">
                    <form class="layui-form layui-form-pane">
                        <div class="layui-form-item">
                            <label class="layui-form-label"> 案例编号：</label>
                            <div class="layui-input-inline">
                                <input class="layui-input" id="txt_CaseCode" autocomplete="off">
                            </div>

                            <label class="layui-form-label"> 寻亲类别：</label>
                            <div class="layui-input-inline">
                                <select id="txt_sl_SRTypeId">
                                    <option value="" selected="selected">==请选择==</option>
                                    <option value="1">家寻亲人</option>
                                    <option value="2">家寻送养</option>
                                    <option value="3">亲人寻家</option>
                                    <option value="4">战友情深</option>
                                    <option value="5">感恩寻人</option>
                                    <option value="6">寻找老友</option>
                                    <option value="7">其他寻人</option>
                                    <option value="8">台海寻亲</option>
                                </select>
                            </div>
                            <label class="layui-form-label">被寻人姓名：</label>
                            <div class="layui-input-inline">
                                <input class="layui-input" id="txt_BeSeekerName" autocomplete="off">
                            </div>
                            <label class="layui-form-label"> 领任务时间：</label>
                            <div class="layui-input-inline">
                                <input type="date" class="layui-input" id="txt_getTaskDate" autocomplete="off">
                            </div>
                        </div>
                    </form>
                    <button class="layui-btn" data-type="reload">搜索</button>
                    <button id="btn_Create" class="layui-btn">新建</button>

                </div>
                

                <table class="layui-hide" id="test"></table>
            </div>

            <script type="text/html" id="barDemo">
                <a onclick="LinkManInfo('{{d.RegisterInfoId}}')" class="layui-btn layui-btn-primary layui-btn-xs" lay-event="detail">联系人信息</a>
                <button onclick="btn_ydbbhj('{{d.RegisterInfoId}}')" class="layui-btn layui-btn-sm layui-btn-normal">引导宝贝回家</button>
                <a onclick="btn_Edit('{{d.RegisterInfoId}}')" class="layui-btn layui-btn-xs" lay-event="edit">设置成功案例</a>
                <button id="btn_ReturnTask('{{d.RegisterInfoId}}')" class="layui-btn layui-btn-sm layui-btn-normal">退任务</button>
                <a onclick="btn_Edit('{{d.RegisterInfoId}}')" class="layui-btn layui-btn-xs" lay-event="edit">编辑</a>
                <a onclick="Del('{{d.RegisterInfoId}}')" class="layui-btn layui-btn-danger layui-btn-xs">删除</a>
            </script>

            <script type="text/html" id="djLink">
                <a href="{{d.RegisterLink}}" class="layui-table-link" target="_blank">{{ d.RegisterLink }}</a>
            </script>

            <script type="text/html" id="ftLink">
                <a href="{{d.PostLink}}" class="layui-table-link" target="_blank">{{ d.PostLink }}</a>
            </script>

            <script>
                layui.use('table', function () {
                    var table = layui.table;

                    var tableIns = table.render({
                        elem: '#test'
                      , url: '/Case/GetAllCase'
                        //, cellMinWidth: 80 //全局定义常规单元格的最小宽度，layui 2.2.1 新增
                      , cols: [[
                        { field: 'CaseCode', title: '案例编号', width: '120' }
                        , { field: 'SRTypeName', title: '寻亲类别', width: '100' } //width 支持：数字、百分比和不填写。你还可以通过 minWidth 参数局部定义当前单元格的最小宽度，layui 2.2.1 新增
                        , { field: 'Title', title: '标题', width: '150' }
                        , { field: 'BeSeekerName', title: '被寻人姓名', width: '100' }
                        , { field: 'getTaskDate', title: '领任务时间', width: '100' }
                        , { field: 'RegisterLink', templet: '#djLink', title: '登记信息', align: 'center', width: '100' } //单元格内容水平居中
                        , { field: 'PostLink', templet: '#ftLink', title: '发帖链接', align: 'left', width: '100' } //单元格内容水平居中
                        , { field: 'Remarks', title: '备注', align: 'left', width: '150' }
                        , { field: 'right', title: '操作', align: 'left', toolbar: '#barDemo', width: '460' }
                      ]]
                      , id: 'testReload'
                      , page: true
                      , limits: [10, 20, 30, 50, 80, 100]
                    });

                    // 搜索
                    var $ = layui.$, active = {
                        reload: function () {
                            //执行重载
                            table.reload('testReload', {
                                page: {
                                    curr: 1 //重新从第 1 页开始
                                }
                              , where: {
                                  whereStr: JSON.stringify(
                                      {
                                          caseCode: $("#txt_CaseCode").val(),
                                          srTypeId: $("#txt_sl_SRTypeId").val(),
                                          beSeekerName: $("#txt_BeSeekerName").val(),
                                          getTaskDate: $("#txt_getTaskDate").val()
                                      })
                              }
                            });
                        }
                    };

                    $('.demoTable .layui-btn').on('click', function () {
                        var type = $(this).data('type');
                        active[type] ? active[type].call(this) : '';
                    });
                });

                $(function () {
                    // 新建
                    $("#btn_Create").click(function () {
                        window.location.href = "/Case/CreateCase";
                    });
                })

                // 联系人信息
                function LinkManInfo(id) {
                    layer.open({
                        type: 2,
                        area: ['500px', '450px'],
                        fixed: false, //不固定
                        maxmin: true,
                        title: '联系人信息',
                        content: '/Case/EditLinManInfo?id=' + id
                    });
                }

                // 编辑案例信息
                function btn_Edit(id) {
                    window.location.href = "/Case/CreateCase?id=" + id;
                };

                // 删除
                function Del(id) {
                    $.post("/Case/DelRegisterInfo", { Id: id }, function (data) {
                        if (data.state) {
                            layer.alert(data.message, { icon: 1 }, function () {
                                window.location.reload();
                            });
                        }
                        else {
                            layer.alert(data.message, { icon: 2 });
                        }
                    }, "json")
                };

                // 引导宝贝回家
                function btn_ydbbhj(id) {
                    layer.confirm('确定引导到宝贝回家？', {
                        btn: ['确定', '取消'] //按钮
                    }, function () {
                        // 确定引导
                        $.post("/Case/ydbbhj", { id: id }, function (data) {
                            if (data.state) {
                                layer.msg(data.message, { icon: 1 },function(){
                                    window.location.reload();
                                });

                            }
                            else {
                                layer.msg(data.message, { icon: 2 });
                                return false;
                            }
                        })
                    }, function () {
                        // 取消
                    });


                    
                }

                // 退任务
                function btn_ReturnTask(id) {

                }

            </script>
        </div>
    </div>
</body>





SRIS/SRIS/Views/Case/CreateCase.cshtml
@model SRIS.ViewModels.RegisterModel

@{
    ViewBag.Title = "创建案例";
    Layout = "~/Views/Shared/_BlankPage.cshtml";
}

<body>
    <div class="main-content">
        <div class="main-content-inner">
            <!-- #section:basics/content.breadcrumbs -->
            <div class="breadcrumbs" id="breadcrumbs">
                <script type="text/javascript">
                    try { ace.settings.check('breadcrumbs', 'fixed') } catch (e) { }
                </script>
                <ul class="breadcrumb">
                    <li>
                        <i class="ace-icon fa fa-home home-icon"></i>
                        @Html.ActionLink("首页", "Index", "Home")
                    </li>
                    <li>
                        @Html.ActionLink("全部案例", "AllCase", "Case")
                    </li>
                    <li class="active">
                    @Html.ActionLink("创建案例", "CreateCase", "Case")
                    </li>
                </ul><!-- /.breadcrumb -->
            </div>
            <div class="page-content">
                <!-- /section:settings.box -->

                <div class="layui-tab layui-tab-card">
                    <ul class="layui-tab-title">
                        <li class="layui-this">案例信息</li>
                        @*<li>联系人信息</li>*@
                    </ul>
                    <div class="layui-tab-content">
                        <div class="layui-tab-item layui-show">
                            <!-- 案例信息开始 -->
                            <div class="row">
                                <div class="col-xs-12">
                                    <!-- PAGE CONTENT BEGINS -->
                                    @using (Html.BeginForm("CreateCase", "Case",FormMethod.Post))
                                    {
                                        @Html.AntiForgeryToken()
                                        @Html.HiddenFor(model=>model.RegisterInfoId)
                                        <div class="form-horizontal">
                                            <hr />
                                            @Html.ValidationSummary(true)
                                            <label class = "layui-form-label">@ViewBag.Message</label>
                                            <div class="layui-form-item">
                                                <div class="layui-inline">
                                                    @Html.LabelFor(model => model.CaseCode, htmlAttributes: new { @class = "layui-form-label" })
                                                    <div class="layui-input-inline">
                                                        @Html.EditorFor(model => model.CaseCode, new { @class = "layui-input" })
                                                        @Html.ValidationMessageFor(model => model.CaseCode)
                                                    </div>
                                                </div>
                                                <div class="layui-inline">
                                                    @Html.LabelFor(model => model.SRTypeId, htmlAttributes: new { @class = "layui-form-label" })
                                                    <div class="layui-input-inline">
                                                        @Html.DropDownListFor(model => model.SRTypeId, ViewBag.select as SelectList, "==请选择==")
                                                        @Html.ValidationMessageFor(model => model.SRTypeId)
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="layui-form-item">
                                                <div class="layui-inline">
                                                    @Html.LabelFor(model => model.Title, new { @class = "layui-form-label" })
                                                    <div class="layui-input-inline">
                                                        @Html.EditorFor(model => model.Title, new { @class = "layui-input" })
                                                        @Html.ValidationMessageFor(model => model.Title)
                                                    </div>
                                                </div>
                                                <div class="layui-inline">
                                                    @Html.LabelFor(model => model.BeSeekerName, htmlAttributes: new { @class = "layui-form-label" })
                                                    <div class="layui-input-inline">
                                                        @Html.EditorFor(model => model.BeSeekerName, new { @class = "layui-input" })
                                                        @Html.ValidationMessageFor(model => model.BeSeekerName)
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="layui-form-item">
                                                <div class="layui-inline">
                                                    @Html.LabelFor(model => model.GetTaskDateTime, new { @class = "layui-form-label" })
                                                    <div class="layui-input-inline">
                                                        @Html.EditorFor(model => model.GetTaskDateTime, new { @class = "layui-input" })
                                                        @Html.ValidationMessageFor(model => model.GetTaskDateTime)
                                                    </div>
                                                </div>
                                                <div class="layui-inline">
                                                    @Html.LabelFor(model => model.RegisterLink, htmlAttributes: new { @class = "layui-form-label" })
                                                    <div class="layui-input-inline">
                                                        @Html.EditorFor(model => model.RegisterLink, new { @class = "layui-input" })
                                                        @Html.ValidationMessageFor(model => model.RegisterLink)
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="layui-form-item layui-form-text">
                                                @*<label class="layui-form-label">文本域</label>*@
                                                @Html.LabelFor(model => model.PostLink, htmlAttributes: new { @class = "layui-form-label" })
                                                <div class="layui-input-block">
                                                    @*<textarea placeholder="请输入内容" class="layui-textarea"></textarea>*@
                                                    @Html.EditorFor(model => model.PostLink, new { @class = "layui-textarea" })
                                                    @Html.ValidationMessageFor(model => model.PostLink)
                                                </div>
                                            </div>

                                            <div class="layui-form-item layui-form-text">
                                                @*<label class="layui-form-label">文本域</label>*@
                                                @Html.LabelFor(model => model.Remarks, htmlAttributes: new { @class = "layui-form-label" })
                                                <div class="layui-input-block">
                                                    @*<textarea placeholder="请输入内容" class="layui-textarea"></textarea>*@
                                                    @Html.TextAreaFor(model => model.Remarks, new { @class = "layui-textarea" })
                                                    @Html.ValidationMessageFor(model => model.Remarks)
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <div class="col-md-offset-2 col-md-10">
                                                    <input type="submit" value="提交" class="btn btn-default" />
                                                </div>
                                            </div>
                                        </div>
                                    }
                                    <!-- PAGE CONTENT ENDS -->
                                </div><!-- /.col -->
                            </div>
                            <!-- 案例信息结束 -->
                        </div>
                        <div class="layui-tab-item">
                            <!-- 联系人信息开始 -->
                            <!-- 联系人信息结束 -->
                        </div>
                    </div>
                </div>




               <!-- /.row -->
            </div><!-- /.page-content -->
        </div>
    </div><!-- /.main-content -->
    <script>
        layui.use('element', function () {
            var $ = layui.jquery
            , element = layui.element; //Tab的切换功能，切换事件监听等，需要依赖element模块

            //触发事件
            var active = {
                tabAdd: function () {
                    //新增一个Tab项
                    element.tabAdd('demo', {
                        title: '新选项' + (Math.random() * 1000 | 0) //用于演示
                      , content: '内容' + (Math.random() * 1000 | 0)
                      , id: new Date().getTime() //实际使用一般是规定好的id，这里以时间戳模拟下
                    })
                }
              , tabDelete: function (othis) {
                  //删除指定Tab项
                  element.tabDelete('demo', '44'); //删除：“商品管理”


                  othis.addClass('layui-btn-disabled');
              }
              , tabChange: function () {
                  //切换到指定Tab项
                  element.tabChange('demo', '22'); //切换到：用户管理
              }
            };

            $('.site-demo-active').on('click', function () {
                var othis = $(this), type = othis.data('type');
                active[type] ? active[type].call(this, othis) : '';
            });

            //Hash地址的定位
            var layid = location.hash.replace(/^#test=/, '');
            element.tabChange('test', layid);

            element.on('tab(test)', function (elem) {
                location.hash = 'test=' + $(this).attr('lay-id');
            });

        });
    </script>
</body>


